<a href="https://colab.research.google.com/github/tomaranjalikumari1994-commits/Data-analyst-projects/blob/main/NLP_Sentiment_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

                                                Text
0                 I love this product,it is amazing!
1      This is worst purchase that I have ever made.
2            It was an okay experience, not too bad.
3  Terrible, the quality is awuful,very disappoin...

    Text Preprocessing
    Text preprocessing is the first and crucial step. It involves cleaning the text and preparing it for further processing. Common preprocessing tasks include:

    Lowercasing: Convert all the text to lowercase to standardize.

    Remove punctuation, special characters, and numbers: Clean the text by removing unnecessary characters.

    Remove extra whitespaces: Strip leading/trailing spaces and reduce multiple spaces between words.

In [ ]:
import string

# Text Preprocessing function
def preprocess_text(text):
    text = text.lower()  # Convert to lowercase
    text = ''.join([char for char in text if char not in string.punctuation])  # Remove punctuation
    text = ' '.join(text.split())  # Remove extra spaces
    return text

df['Processed_Text'] = df['Text'].apply(preprocess_text)
print()
df[['Text', 'Processed_Text']]

,Text,Processed_Text
0,"I love this product, it is amazing!",i love this product it is amazing
1,This is the worst purchase I have ever made.,this is the worst purchase i have ever made
2,"It was an okay experience, not too bad.",it was an okay experience not too bad
3,Absolutely fantastic! I will buy again.,absolutely fantastic i will buy again
4,"Terrible, the quality is awful, very disappoin...",terrible the quality is awful very disappointed

    Tokenization
    Tokenization involves splitting text into individual words or tokens. It is a crucial step as the model works with individual tokens rather than raw text.

In [ ]:
from nltk.tokenize import word_tokenize

#Tokenization

,Processed_Text,Tokens
0,i love this product it is amazing,"[i, love, this, product, it, is, amazing]"
1,this is the worst purchase i have ever made,"[this, is, the, worst, purchase, i, have, ever..."
2,it was an okay experience not too bad,"[it, was, an, okay, experience, not, too, bad]"
3,absolutely fantastic i will buy again,"[absolutely, fantastic, i, will, buy, again]"
4,terrible the quality is awful very disappointed,"[terrible, the, quality, is, awful, very, disa..."

    Stopword Removal
    Stopwords are common words that don't carry significant meaning and can be safely removed from the text. Common stopwords include 'the', 'is', 'in', 'a', etc

In [ ]:
from nltk.corpus import stopwords

# Stopword removal
stop_words = set(stopwords.words('english'))

def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['Tokens_No_Stopwords'] = df['Tokens'].apply(remove_stopwords)
#print(df[['Tokens', 'Tokens_No_Stopwords']])
df[['Tokens', 'Tokens_No_Stopwords']]

,Tokens,Tokens_No_Stopwords
0,"[i, love, this, product, it, is, amazing]","[love, product, amazing]"
1,"[this, is, the, worst, purchase, i, have, ever...","[worst, purchase, ever, made]"
2,"[it, was, an, okay, experience, not, too, bad]","[okay, experience, bad]"
3,"[absolutely, fantastic, i, will, buy, again]","[absolutely, fantastic, buy]"
4,"[terrible, the, quality, is, awful, very, disa...","[terrible, quality, awful, disappointed]"

In [ ]:
from nltk.stem import PorterStemmer

# Stemming
stemmer = PorterStemmer()

def stem_tokens(tokens):
    return [stemmer.stem(word) for word in tokens]

df['Stemmed_Tokens'] = df['Tokens_No_Stopwords'].apply(stem_tokens)
#print(df[['Tokens_No_Stopwords', 'Stemmed_Tokens']])
df[['Tokens_No_Stopwords', 'Stemmed_Tokens']]

,Tokens_No_Stopwords,Stemmed_Tokens
0,"[love, product, amazing]","[love, product, amaz]"
1,"[worst, purchase, ever, made]","[worst, purchas, ever, made]"
2,"[okay, experience, bad]","[okay, experi, bad]"
3,"[absolutely, fantastic, buy]","[absolut, fantast, buy]"
4,"[terrible, quality, awful, disappointed]","[terribl, qualiti, aw, disappoint]"

In [ ]:
n considers the context and produces meaningful base forms of words.

    Bag of Words (BOW)
    The Bag of Words (BOW) model represents text data as a matrix of token counts. Each unique token from the corpus is a feature.

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# BOW Model
vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(df['Processed_Text'])
#print(pd.DataFrame(X_bow.toarray(), columns=vectorizer.get_feature_names()))
df_final = pd.DataFrame(X_bow.toarray(), columns=vectorizer.get_feature_names())
df_final

,absolutely,again,amazing,an,awful,bad,buy,disappointed,ever,experience,...,purchase,quality,terrible,the,this,too,very,was,will,worst
0,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0,...,1,0,0,1,1,0,0,0,0,1
2,0,0,0,1,0,1,0,0,0,1,...,0,0,0,0,0,1,0,1,0,0
3,1,1,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,1,0,0,1,0,0,...,0,1,1,1,0,0,1,0,0,0

    TF-IDF (Term Frequency - Inverse Document Frequency)
    TF-IDF is a statistical measure used to evaluate how important a word is to a document in a collection or corpus. It assigns higher weights to words that are frequent in a specific document but rare across other documents.

In [ ]:

# TF-IDF Model
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(df['Processed_Text'])
#print(pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names_out()))
tf_data = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names())
tf_data

,absolutely,again,amazing,an,awful,bad,buy,disappointed,ever,experience,...,purchase,quality,terrible,the,this,too,very,was,will,worst
0,0.000000,0.000000,0.458815,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.370169,0.000000,0.000000,0.000000,0.000000,0.00000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.38489,0.000000,...,0.38489,0.000000,0.000000,0.310527,0.310527,0.000000,0.000000,0.000000,0.000000,0.38489
2,0.000000,0.000000,0.000000,0.361529,0.000000,0.361529,0.000000,0.000000,0.00000,0.361529,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.361529,0.000000,0.361529,0.000000,0.00000
3,0.447214,0.447214,0.000000,0.000000,0.000000,0.000000,0.447214,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.447214,0.00000
4,0.000000,0.000000,0.000000,0.000000,0.404907,0.000000,0.000000,0.404907,0.00000,0.000000,...,0.00000,0.404907,0.404907,0.326676,0.000000,0.000000,0.404907,0.000000,0.000000,0.00000

In [ ]:
tf_data.reset_index()

,index,absolutely,again,amazing,an,awful,bad,buy,disappointed,ever,...,purchase,quality,terrible,the,this,too,very,was,will,worst
0,0,0.000000,0.000000,0.458815,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.370169,0.000000,0.000000,0.000000,0.000000,0.00000
1,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.38489,...,0.38489,0.000000,0.000000,0.310527,0.310527,0.000000,0.000000,0.000000,0.000000,0.38489
2,2,0.000000,0.000000,0.000000,0.361529,0.000000,0.361529,0.000000,0.000000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.361529,0.000000,0.361529,0.000000,0.00000
3,3,0.447214,0.447214,0.000000,0.000000,0.000000,0.000000,0.447214,0.000000,0.00000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.447214,0.00000
4,4,0.000000,0.000000,0.000000,0.000000,0.404907,0.000000,0.000000,0.404907,0.00000,...,0.00000,0.404907,0.404907,0.326676,0.000000,0.000000,0.404907,0.000000,0.000000,0.00000

In [ ]:
tf_data

,absolutely,again,amazing,an,awful,bad,buy,disappointed,ever,experience,...,purchase,quality,terrible,the,this,too,very,was,will,worst
0,0.000000,0.000000,0.458815,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.370169,0.000000,0.000000,0.000000,0.000000,0.00000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.38489,0.000000,...,0.38489,0.000000,0.000000,0.310527,0.310527,0.000000,0.000000,0.000000,0.000000,0.38489
2,0.000000,0.000000,0.000000,0.361529,0.000000,0.361529,0.000000,0.000000,0.00000,0.361529,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.361529,0.000000,0.361529,0.000000,0.00000
3,0.447214,0.447214,0.000000,0.000000,0.000000,0.000000,0.447214,0.000000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.447214,0.00000
4,0.000000,0.000000,0.000000,0.000000,0.404907,0.000000,0.000000,0.404907,0.00000,0.000000,...,0.00000,0.404907,0.404907,0.326676,0.000000,0.000000,0.404907,0.000000,0.000000,0.00000

In [ ]:
X_tfidf

<5x29 sparse matrix of type '<class 'numpy.float64'>'
	with 34 stored elements in Compressed Sparse Row format>

    Skipgram (Word2Vec)
    The Skipgram model is used to train word embeddings, where a word is represented in vector form. If you're working on word embeddings, the Skipgram model from Word2Vec can help. This is more advanced and can be done using libraries like gensim.

In [ ]:
# ! pip install gensim --user

In [ ]:
from gensim.models import Word2Vec

# Training Skipgram model (Word2Vec)
model = Word2Vec(df['Tokens_No_Stopwords'], vector_size=50, window=3, min_count=1, sg=1)
model.save("skipgram.model")

# View vector for the word "product"
print(len(model.wv['product']))
#print(model.wv['product'])

50

In [ ]:
print(model.wv['product'])

[-0.01723938  0.00733148  0.01037977  0.01148388  0.01493384 -0.01233535
  0.00221123  0.01209456 -0.0056801  -0.01234705 -0.00082045 -0.0167379
 -0.01120002  0.01420908  0.00670508  0.01445134  0.01360049  0.01506148
 -0.00757831 -0.00112361  0.00469675 -0.00903806  0.01677746 -0.01971633
  0.01352928  0.00582883 -0.00986566  0.00879638 -0.00347915  0.01342277
  0.0199297  -0.00872489 -0.00119868 -0.01139127  0.00770164  0.00557325
  0.01378215  0.01220219  0.01907699  0.01854683  0.01579614 -0.01397901
 -0.01831173 -0.00071151 -0.00619968  0.01578863  0.01187715 -0.00309133
  0.00302193  0.00358008]

# This step is not mandatory for all sentiment classification tasks, but it helps capture deeper semantic meaning in the words.

# Pre-trained Models for Sentiment Analysis if  you dont have sentiment column otherwise you can directly apply any ML algoritmn

    Hugging Face Transformers (e.g., BERT, RoBERTa)
    Hugging Face provides a variety of pre-trained models for sentiment analysis, including BERT, DistilBERT, RoBERTa, and more. These models are very powerful for NLP tasks and can be used to classify sentiment with high accuracy.

In [ ]:
#!pip install transformers

In [ ]:
from transformers import pipeline

# Load a pre-trained sentiment analysis model
sentiment_model = pipeline('sentiment-analysis')

# Provide new text data for sentiment analysis
text = "I love this product! It's amazing."

# Get the sentiment label (positive/negative) and score
result = sentiment_model(text)

print(result)

No model was supplied, defaulted to distilbert/distilbert-base-uncased-finetuned-sst-2-english and revision 714eb0f (https://huggingface.co/distilbert/distilbert-base-uncased-finetuned-sst-2-english).
Using a pipeline without specifying a model name and revision in production is not recommended.

[{'label': 'POSITIVE', 'score': 0.9998866319656372}]

In [ ]:
# Provide new t

[{'label': 'NEGATIVE', 'score': 0.999757707118988}]

In [ ]:
# Provide new text data for sentiment analysis
text = "It is having average quality"

# Get the sentiment label (positive/negative) and score
result = sentiment_model(text)

print(result)

[{'label': 'POSITIVE', 'score': 0.9835954904556274}]

In [ ]:
VADER (Valence Aware Dictionary and sEntiment Reasoner)
VADER is a simple and fast tool for sentiment analysis. It works well on social media texts, short sentences, and is pre-trained to handle sentiment classification.

In [ ]:
#!pip install vaderSentiment

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Initialize the VADER sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

# Provide some text for analysis
text = "I absolutely hate waiting in long lines!"

# Get the sentiment scores
scores = analyzer.polarity_scores(text)

# Classify sentiment as positive, negative, or neutral
if scores['compound'] >= 0.05:
    sentiment = 'positive'
elif scores['compound'] <= -0.05:
    sentiment = 'negative'
else:
    sentiment = 'neutral'

print(f"Sentiment: {sentiment}")

Sentiment: negative

In [ ]:
scores

{'neg': 0.417, 'neu': 0.583, 'pos': 0.0, 'compound': -0.6468}

In [ ]:
# Provide some text for analysis
text = "I absolutely love waiting in long lines!"

# Get the sentiment scores
scores = analyzer.polarity_scores(text)

# Classify sentiment as positive, negative, or neutral
if scores['compound'] >= 0.05:
    sentiment = 'positive'
elif scores['compound'] <= -0.05:
    sentiment = 'negative'
else:
    sentiment = 'neutral'

print(f"Sentiment: {sentiment}")

Sentiment: positive

In [ ]:
scores

{'neg': 0.0, 'neu': 0.556, 'pos': 0.444, 'compound': 0.6989}

    TextBlob
    TextBlob is another popular NLP library with built-in sentiment analysis. It uses a simple rule-based approach to assign a sentiment polarity score and subjectivity score.

In [ ]:
#!pip install textblob

In [ ]:
from textblob import TextBlob

# Provide the text for analysis
text = "I like my new phone!"

# Create a TextBlob object
blob = TextBlob(text)

# Get the polarity (sentiment score)
polarity = blob.sentiment.polarity

# Classify sentiment
if polarity > 0:
    sentiment = 'positive'
elif polarity < 0:
    sentiment = 'negative'
else:
    sentiment = 'neutral'

print(f"Sentiment: {sentiment}")

Sentiment: positive

In [ ]:
blob

TextBlob("I like my new phone!")

In [ ]:
polarity

0.17045454545454544

    Transformers + Hugging Face (for multi-class classification: Positive, Negative, Neutral)
    For more detailed classification (like positive, negative, and neutral), you can also use models fine-tuned specifically for multi-class sentiment classification

    https://huggingface.co/j-hartmann/emotion-english-distilroberta-base

In [ ]:
from transformers import pipeline

# Load a pre-trained sentiment analysis model
sentiment_model = pipeline('text-classification', model='j-hartmann/emotion-english-distilroberta-base')

# Provide text for analysis
text = "I'm feeling so bad today!"

# Get the result
result = sentiment_model(text)

print(result)

pytorch_model.bin:   0%|          | 0.00/329M [00:00<?, ?B/s]

C:\Users\hp\AppData\Roaming\Python\Python38\site-packages\huggingface_hub\file_download.py:159: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\hp\.cache\huggingface\hub\models--j-hartmann--emotion-english-distilroberta-base. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to see activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

[{'label': 'sadness', 'score': 0.978950560092926}]

In [ ]:
# Provide text for analysis
text = "i will beat you up"

# Get the result
result = sentiment_model(text)

print(result)

[{'label': 'POSITIVE', 'score': 0.9931426048278809}]

    To achieve your goal of providing new data and getting sentiment classification (positive, negative, neutral), you can wrap any of the pre-trained models mentioned above into a function.

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

# Initialize the VADER sentiment analyzer
analyzer = SentimentIntensityAnalyzer()

def classify_sentiment(text):
    # Get the sentiment scores
    scores = analyzer.polarity_scores(text)

    # Classify sentiment as positive, negative, or neutral
    if scores['compound'] >= 0.05:
        return 'positive'
    elif scores['compound'] <= -0.05:
        return 'negative'
    else:
        return 'neutral'

# Example usage with new data
new_text = "I'm having a great day!"
sentiment = classify_sentiment(new_text)
print(f"Sentiment: {sentiment}")

Sentiment: positive

                                                Text Sentiment
0                I love this product, it is amazing!  positive
1       This is the worst purchase I have ever made.  negative
2            It was an okay experience, not too bad.   neutral
3            Absolutely fantastic! I will buy again.  positive
4  Terrible, the quality is awful, very disappoin...  negative

In [ ]:
# TF-IDF Transformation
tfidf_vectorizer = TfidfVectorizer()
X_tfidf = tfidf_vectorizer.fit_transform(df['Text'])
X_tfidf

<5x29 sparse matrix of type '<class 'numpy.float64'>'
	with 34 stored elements in Compressed Sparse Row format>

In [ ]:
# tf_data = pd.DataFrame(X_tfidf.toarray(), columns=tfidf_vectorizer.get_feature_names())
# tf_data

In [ ]:
# Splitting data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_tfidf, df['Sentiment'], test_size=0.2, random_state=42)

In [ ]:
X_train

<4x29 sparse matrix of type '<class 'numpy.float64'>'
	with 26 stored elements in Compressed Sparse Row format>

In [ ]:
X_test

<1x29 sparse matrix of type '<class 'numpy.float64'>'
	with 8 stored elements in Compressed Sparse Row format>

In [ ]:
y_train

4    negative
2     neutral
0    positive
3    positive
Name: Sentiment, dtype: object

In [ ]:
y_test

1    negative
Name: Sentiment, dtype: object

              precision    recall  f1-score   support

    negative       0.00      0.00      0.00       1.0
    positive       0.00      0.00      0.00       0.0

    accuracy                           0.00       1.0
   macro avg       0.00      0.00      0.00       1.0
weighted avg       0.00      0.00      0.00       1.0

The sentiment of the new text is: positive

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))